### ISSUE TITLE
-_-

### ISSUE THREAD

**Issue by ksdme** [prashantxc/birthdays#1]
![image](https://user-images.githubusercontent.com/12156014/61375764-53d0f800-a8bd-11e9-9140-1fa13623c642.png)

**Comment by ksdme** [comment]
![image](https://user-images.githubusercontent.com/12156014/61632724-2e702f80-acab-11e9-9b5b-2062200e23e6.png)

**Comment by prashantxc** [comment]
This issue has been closed with an error code 3105[birthday not found]
